CREATE database OnlyFifty;
USE OnlyFifty;

CREATE TABLE GERIATRA(
ID_GERIATRA INT PRIMARY	KEY,
NOMBRE_GERIATRA VARCHAR(50),
NUM_CELULAR VARCHAR(11),
CORREO_ELECTRONICO VARCHAR(50),
FOTO varchar(500),
CLAVE VARCHAR(8),
ESTADO_GERIATRA BIT default 1);

CREATE TABLE PACIENTE(
ID_PACIENTE INT PRIMARY KEY,
NOMBRE_PACIENTE VARCHAR(50),
EDAD_PACIENTE INT(2),
FOTO_PACIENTE varchar(500),
ESTADO_PACIENTE BIT default 1,
GERIATRA_ID INT,
RH varchar(5),
Genero varchar(20),
Contacto_Familiar varchar(15),
foreign key (GERIATRA_ID) REFERENCES GERIATRA(ID_GERIATRA));

CREATE TABLE CITAS_MEDICAS(
ID_CITA INT auto_increment primary KEY,
LUGAR VARCHAR(50),
Profesional_Cargo VARCHAR(50),
HORA TIME,
FECHA DATE,
PACIENTE_ID INT,
foreign key (PACIENTE_ID) REFERENCES PACIENTE(ID_PACIENTE));

CREATE TABLE MEDICAMENTOS(
ID_MEDICAMENTOS INT auto_increment primary KEY,
NOMBRE_Comercial VARCHAR(50),
Nombre_Generico varchar(50),
Via_Administracion varchar(50),
Cantidad_Unidades varchar(50),
Lote varchar(50),
LABORATORIO VARCHAR(80));

CREATE TABLE TRATAMIENTO(
ID_TRATAMIENTO INT auto_increment primary KEY,
Diagnostico VARCHAR(50),
DOSIS varchar(50),
FRECUENCIA VARCHAR(50),
Observaciones VARCHAR(200),
HORA_EXACTA TIME) ;     

CREATE TABLE TRATAMIENTO_MEDICAMENTOS(
TRATAMIENTO_ID INT,
MEDICAMENTOS_ID INT,
FOREIGN KEY (TRATAMIENTO_ID) REFERENCES TRATAMIENTO(ID_TRATAMIENTO),
FOREIGN KEY (MEDICAMENTOS_ID) REFERENCES MEDICAMENTOS(ID_MEDICAMENTOS));

CREATE TABLE ENFERMEDADES(
ID_ENFERMEDAD INT auto_increment primary KEY,
NOMBRE_ENFEREDAD VARCHAR(50),
TRATAMIENTO_ID INT,
FOREIGN KEY (TRATAMIENTO_ID) REFERENCES TRATAMIENTO(ID_TRATAMIENTO));

CREATE TABLE ENFERMEDADES_PACIENTES(
ENFERMDAD_ID INT,
PACIENTE_ID INT,
FOREIGN KEY (ENFERMDAD_ID) REFERENCES ENFERMEDADES(ID_ENFERMEDAD),
FOREIGN KEY (PACIENTE_ID) REFERENCES PACIENTE(ID_PACIENTE));